Repository MicrosoftDocs/powerbi-docs.ko-kr, pull requests merged in 2019-12, with the labels that each got.

#630 Update service-connect-to-smartsheet.md
  powerbi-docs/service-connect-to-smartsheet.md
Labels: Accepted, Linguistic Suggestion

#633 Update service-organizational-content-pack-create-and-publish.md
  powerbi-docs/service-organizational-content-pack-create-and-publish.md
Labels: Accepted, Linguistic Suggestion

#637 Update mobile-apps-data-in-real-world-context.md
  powerbi-docs/consumer/mobile/mobile-apps-data-in-real-world-context.md
Labels: Accepted, Linguistic Suggestion

#632 Update service-connect-to-zendesk.md
  powerbi-docs/service-connect-to-zendesk.md
Labels: Accepted, Linguistic Suggestion

#634 Update mobile-apps-for-mobile-devices.md
  powerbi-docs/consumer/mobile/mobile-apps-for-mobile-devices.md
Labels: Accepted, Linguistic Suggestion

#635 Update end-user-app-marketing.md
  powerbi-docs/consumer/end-user-app-marketing.md
Labels: Accepted, Linguistic Suggestion

#636 Update tutorial-mobile-apps-ios-qna.md
  powerbi-docs/consumer/mobile/tutorial-mobile-apps-ios-qna.md
Labels: Accepted, Linguistic Suggestion

#638 Update mobile-apps-offline-data.md
  powerbi-docs/consumer/mobile/mobile-apps-offline-data.md
Labels: Accepted, Linguistic Suggestion

#639 Update mobile-apps-view-dashboard.md
  powerbi-docs/consumer/mobile/mobile-apps-view-dashboard.md
Labels: Accepted, Linguistic Suggestion

#641 Update mobile-tiles-in-the-mobile-apps.md
  powerbi-docs/consumer/mobile/mobile-tiles-in-the-mobile-apps.md
Labels: Accepted, Linguistic Suggestion

#640 Update mobile-reports-in-the-mobile-apps.md
  powerbi-docs/consumer/mobile/mobile-reports-in-the-mobile-apps.md
Labels: Accepted, Linguistic Suggestion

#642 Update desktop-ai-insights.md
  powerbi-docs/desktop-ai-insights.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#643 Update power-bi-visualization-decomposition-tree.md
  powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md
Labels: Accepted, Linguistic Suggestion

#644 Update mobile-share-dashboard-from-the-mobile-apps.md
  powerbi-docs/consumer/mobile/mobile-share-dashboard-from-the-mobile-apps.md
Labels: Accepted, Linguistic Suggestion

#645 Update mobile-apps-favorites.md
  powerbi-docs/consumer/mobile/mobile-apps-favorites.md
Labels: Accepted, Linguistic Suggestion

#646 Update mobile-set-data-alerts-in-the-mobile-apps.md
  powerbi-docs/consumer/mobile/mobile-set-data-alerts-in-the-mobile-apps.md
Labels: Accepted, Linguistic Suggestion

#651 Update service-upgrade-workspaces.md
  powerbi-docs/designer/service-upgrade-workspaces.md
Labels: Accepted, Linguistic Suggestion

#648 Update mobile-apps-geographic-filtering.md
  powerbi-docs/consumer/mobile/mobile-apps-geographic-filtering.md
Labels: Accepted, Linguistic Suggestion

#652 Update mobile-app-ssrs-kpis-mobile-on-premises-reports.md
  powerbi-docs/consumer/mobile/mobile-app-ssrs-kpis-mobile-on-premises-reports.md
Labels: Accepted, Linguistic Suggestion

#653 Update mobile-annotate-and-share-a-tile-from-the-mobile-apps.md
  powerbi-docs/consumer/mobile/mobile-annotate-and-share-a-tile-from-the-mobile-apps.md
Labels: Accepted, Linguistic Suggestion

#649 Update mobile-oauth-ssrs.md
  powerbi-docs/consumer/mobile/mobile-oauth-ssrs.md
Labels: Linguistic Suggestion, Partially Accepted

#650 Update mobile-apps-view-phone-report.md
  powerbi-docs/consumer/mobile/mobile-apps-view-phone-report.md
Labels: Linguistic Suggestion, Partially Accepted

#655 Update mobile-iphone-app-get-started.md
  powerbi-docs/consumer/mobile/mobile-iphone-app-get-started.md
Labels: Accepted, Linguistic Suggestion

#657 Update mobile-apple-watch.md
  powerbi-docs/consumer/mobile/mobile-apple-watch.md
Labels: Accepted, Linguistic Suggestion

#656 Update mobile-apps-ios-qna.md
  powerbi-docs/consumer/mobile/mobile-apps-ios-qna.md
Labels: Accepted, Linguistic Suggestion

#659 Update mobile-android-app-get-started.md
  powerbi-docs/consumer/mobile/mobile-android-app-get-started.md
Labels: Accepted, Linguistic Suggestion

#658 some word change
  powerbi-docs/natural-language/q-and-a-tooling-teach-q-and-a.md
Labels: Accepted, Linguistic Suggestion

#661 Update mobile-app-windows-10-ssrs-kpis-mobile-reports.md
  powerbi-docs/consumer/mobile/mobile-app-windows-10-ssrs-kpis-mobile-reports.md
Labels: Accepted, Linguistic Suggestion

#662 Update service-admin-faq.md
  powerbi-docs/service-admin-faq.md
Labels: Accepted, Linguistic Suggestion

#663 Update service-admin-portal.md
  powerbi-docs/service-admin-portal.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#667 Update rls-usernames.md
  powerbi-docs/includes/rls-usernames.md
Labels: Accepted

#664 Update service-admin-azure-ad-b2b.md
  powerbi-docs/service-admin-azure-ad-b2b.md
Labels: Linguistic Suggestion, Partially Accepted

#660 Update mobile-windows-10-phone-app-get-started.md
  powerbi-docs/consumer/mobile/mobile-windows-10-phone-app-get-started.md
Labels: Linguistic Suggestion, Partially Accepted

#668 Update service-admin-mobile-intune.md
  powerbi-docs/service-admin-mobile-intune.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#665 Update rls-desktop-define-roles.md
  powerbi-docs/includes/rls-desktop-define-roles.md
Labels: Accepted, Linguistic Suggestion

#670 Update service-admin-power-bi-security.md
  powerbi-docs/service-admin-power-bi-security.md
Labels: Accepted, Linguistic Suggestion

#666 Update service-admin-rls.md
  powerbi-docs/service-admin-rls.md
Labels: Accepted, Linguistic Suggestion

#671 Update dax-error-functions.md
  powerbi-docs/guidance/dax-error-functions.md
Labels: Accepted, Linguistic Suggestion

#672 Update whitepaper-powerbi-security.md
  powerbi-docs/whitepaper-powerbi-security.md
Labels: Accepted, Linguistic Suggestion

#673 Update whitepaper-powerbi-premium-deployment.md
  powerbi-docs/whitepaper-powerbi-premium-deployment.md
Labels: Accepted, Linguistic Suggestion

#676 Update paginated-reports-quickstart-aw.md
  powerbi-docs/paginated-reports-quickstart-aw.md
Labels: Accepted, Linguistic Suggestion

#681 Update service-get-started.md
  powerbi-docs/service-get-started.md
Labels: Accepted, Linguistic Suggestion

#674 Update whitepaper-powerbi-security.md
  powerbi-docs/whitepaper-powerbi-security.md
Labels: Accepted, Linguistic Suggestion

#685 Update power-bi-visualization-influencers.md
  powerbi-docs/visuals/power-bi-visualization-influencers.md
Labels: Accepted, Linguistic Suggestion

#687 Update service-gateway-sql-tutorial.md
  powerbi-docs/service-gateway-sql-tutorial.md
Labels: Accepted, Linguistic Suggestion

#675 Update whitepaper-powerbi-security.md
  powerbi-docs/whitepaper-powerbi-security.md
Labels: Linguistic Suggestion, Partially Accepted

#678 Update whitepaper-azure-b2b-power-bi.md
  powerbi-docs/whitepaper-azure-b2b-power-bi.md
Labels: Accepted, Linguistic Suggestion

#677 Update whitepaper-powerbi-security.md
  powerbi-docs/whitepaper-powerbi-security.md
Labels: Accepted, Linguistic Suggestion

#679 Update whitepaper-powerbi-security.md
  powerbi-docs/whitepaper-powerbi-security.md
Labels: Accepted, Linguistic Suggestion

#680 Update whitepaper-azure-b2b-power-bi.md
  powerbi-docs/whitepaper-azure-b2b-power-bi.md
Labels: Accepted, Linguistic Suggestion

#682 Update whitepaper-azure-b2b-power-bi.md
  powerbi-docs/whitepaper-azure-b2b-power-bi.md
Labels: Accepted, Linguistic Suggestion

#683 Update service-tutorial-connect-to-github.md
  powerbi-docs/service-tutorial-connect-to-github.md
Labels: Accepted, Linguistic Suggestion

#684 Update whitepaper-azure-b2b-power-bi.md
  powerbi-docs/whitepaper-azure-b2b-power-bi.md
Labels: Accepted, Linguistic Suggestion

#689 Update end-user-q-and-a.md
  powerbi-docs/consumer/end-user-q-and-a.md
Labels: Accepted, Linguistic Suggestion

#690 Update service-data-classification.md
  powerbi-docs/service-data-classification.md
Labels: Accepted, Linguistic Suggestion
