Repository MicrosoftDocs/powerbi-docs.ko-kr, pull requests merged in 2019-03, with the labels that each got.

#98 Update power-bi-visualization-waterfall-charts.md
  powerbi-docs/visuals/power-bi-visualization-waterfall-charts.md
Labels: Accepted, Linguistic Suggestion

#99 Update service-analytics-pane.md
  powerbi-docs/service-analytics-pane.md
Labels: Accepted, Linguistic Suggestion

#101 Update service-dashboard-tiles.md
  powerbi-docs/service-dashboard-tiles.md
Labels: Accepted, Linguistic Suggestion

#102 Update service-dashboard-copy.md
  powerbi-docs/service-dashboard-copy.md
Labels: Accepted, Linguistic Suggestion

#103 Update service-dashboards.md
  powerbi-docs/service-dashboards.md
Labels: Linguistic Suggestion, Partially Accepted

#104 Update power-bi-visualization-introduction-to-q-and-a.md
  powerbi-docs/power-bi-visualization-introduction-to-q-and-a.md
Labels: Accepted, Linguistic Suggestion

#106 Update service-q-and-a-create-featured-questions.md
  powerbi-docs/service-q-and-a-create-featured-questions.md
Labels: Accepted, Linguistic Suggestion

#123 Update quickstart-create-paginated-report.md
  powerbi-docs/report-server/quickstart-create-paginated-report.md
Labels: Linguistic Suggestion, Partially Accepted

#122 Update data-sources.md
  powerbi-docs/report-server/data-sources.md
Labels: Accepted, Linguistic Suggestion

#107 Update service-cortana-answer-cards.md
  powerbi-docs/service-cortana-answer-cards.md
Labels: Accepted, Linguistic Suggestion

#108 Update service-cortana-intro.md
  powerbi-docs/service-cortana-intro.md
Labels: Accepted, Linguistic Suggestion

#109 Update service-cortana-enable.md
  powerbi-docs/service-cortana-enable.md
Labels: Accepted, Linguistic Suggestion

#121 Update install-powerbi-desktop.md
  powerbi-docs/report-server/install-powerbi-desktop.md
Labels: Accepted, Linguistic Suggestion

#120 Update service-admin-rls.md
  powerbi-docs/service-admin-rls.md
Labels: Accepted, Linguistic Suggestion

#119 Update service-delete.md
  powerbi-docs/service-delete.md
Labels: Accepted, Linguistic Suggestion

#110 Update service-insights.md
  powerbi-docs/service-insights.md
Labels: Linguistic Suggestion, Partially Accepted

#111 Update service-insights-optimize.md
  powerbi-docs/service-insights-optimize.md
Labels: Accepted, Linguistic Suggestion

#118 Update service-admin-troubleshooting-power-bi-personal-gateway.md
  powerbi-docs/service-admin-troubleshooting-power-bi-personal-gateway.md
Labels: Accepted, Linguistic Suggestion

#117 Update service-publish-to-web.md
  powerbi-docs/service-publish-to-web.md
Labels: Linguistic Suggestion, Partially Accepted

#116 Update service-report-subscribe.md
  powerbi-docs/service-report-subscribe.md
Labels: In Progress, Linguistic Suggestion

#115 Update service-share-reports.md
  powerbi-docs/service-share-reports.md
Labels: Accepted, Linguistic Suggestion

#114 Update service-share-dashboards.md
  powerbi-docs/service-share-dashboards.md
Labels: Accepted, Linguistic Suggestion

#112 Update service-create-the-new-workspaces.md
  powerbi-docs/service-create-the-new-workspaces.md
Labels: Accepted, Linguistic Suggestion

#113 Update service-create-distribute-apps.md
  powerbi-docs/service-create-distribute-apps.md
Labels: Accepted, Linguistic Suggestion

#124 Update add-comments.md
  powerbi-docs/report-server/add-comments.md
Labels: Accepted, Linguistic Suggestion

#125 Update configure-scheduled-refresh.md
  powerbi-docs/report-server/configure-scheduled-refresh.md
Labels: Accepted, Linguistic Suggestion

#126 Update paginated-reports-enter-data.md
  powerbi-docs/paginated-reports-enter-data.md
Labels: Accepted, Linguistic Suggestion

#127 Update paginated-reports-quickstart-aw.md
  powerbi-docs/paginated-reports-quickstart-aw.md
Labels: Linguistic Suggestion, Partially Accepted

#129 Update paginated-reports-embedded-data-source.md
  powerbi-docs/paginated-reports-embedded-data-source.md
Labels: Accepted, Linguistic Suggestion

#128 Update paginated-reports-enter-data.md
  powerbi-docs/paginated-reports-enter-data.md
Labels: Linguistic Suggestion

#130 Update paginated-reports-create-embedded-dataset.md
  powerbi-docs/paginated-reports-create-embedded-dataset.md
Labels: Accepted, Linguistic Suggestion

#132 Update service-admin-premium-purchase.md
  powerbi-docs/service-admin-premium-purchase.md
Labels: Linguistic Suggestion, Partially Accepted

#133 Update service-premium-large-datasets.md
  powerbi-docs/service-premium-large-datasets.md
Labels: Accepted, Linguistic Suggestion

#131 Update service-premium-understand-how-it-works.md
  powerbi-docs/service-premium-understand-how-it-works.md
Labels: Accepted, In Progress, Linguistic Suggestion

#143 Update embed-sample-for-customers.md
  powerbi-docs/developer/embed-sample-for-customers.md
Labels: Linguistic Suggestion, Partially Accepted

#139 Update service-admin-syndication-partner.md
  powerbi-docs/service-admin-syndication-partner.md
Labels: Accepted, Linguistic Suggestion

#136 Update service-admin-licensing-organization.md
  powerbi-docs/service-admin-licensing-organization.md
Labels: Accepted, Linguistic Suggestion

#138 Update service-admin-purchasing-power-bi-pro.md
  powerbi-docs/service-admin-purchasing-power-bi-pro.md
Labels: Linguistic Suggestion, Partially Accepted

#140 Update service-admin-portal.md
  powerbi-docs/service-admin-portal.md
Labels: Linguistic Suggestion

#141 Update service-admin-auditing.md
  powerbi-docs/service-admin-auditing.md
Labels: Linguistic Suggestion

#145 Update embed-service-principal.md
  powerbi-docs/developer/embed-service-principal.md
Labels: Accepted, Linguistic Suggestion

#146 Update embedded-row-level-security.md
  powerbi-docs/developer/embedded-row-level-security.md
Labels: Linguistic Suggestion

#147 Update embedded-faq.md
  powerbi-docs/developer/embedded-faq.md
Labels: Linguistic Suggestion, Partially Accepted

#149 Update qanda.md
  powerbi-docs/developer/qanda.md
Labels: Accepted, Linguistic Suggestion

#151 Update migrate-from-powerbi-embedded.md
  powerbi-docs/developer/migrate-from-powerbi-embedded.md
Labels: Linguistic Suggestion, Partially Accepted

#148 Update register-app.md
  powerbi-docs/developer/register-app.md
Labels: Linguistic Suggestion, Partially Accepted

#150 Update azure-pbie-pause-start.md
  powerbi-docs/developer/azure-pbie-pause-start.md
Labels: Accepted, Linguistic Suggestion

#157 Update api-dataset-properties.md
  powerbi-docs/developer/api-dataset-properties.md
Labels: Accepted, Linguistic Suggestion

#152 Update power-bi-custom-visuals.md
  powerbi-docs/power-bi-custom-visuals.md
Labels: Accepted, Linguistic Suggestion

#160 Change Dax function
  powerbi-docs/desktop-calculated-tables.md
Labels: In Progress

#154 Update custom-visual-develop-tutorial-format-options.md
  powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md
Labels: Linguistic Suggestion, Partially Accepted

#155 Update power-bi-custom-visuals-organization.md
  powerbi-docs/power-bi-custom-visuals-organization.md
Labels: In Progress, Linguistic Suggestion

#156 Update power-bi-custom-visuals-faq.md
  powerbi-docs/power-bi-custom-visuals-faq.md
Labels: Linguistic Suggestion, Partially Accepted

#164 Change the word
  powerbi-docs/desktop-calculated-tables.md
Labels: In Progress
