Repository MicrosoftDocs/powerbi-docs.ko-kr, pull requests merged in 2019-05, with the labels that each got.

#228 Update power-bi-visualization-funnel-charts.md
  powerbi-docs/visuals/power-bi-visualization-funnel-charts.md
Labels: In Progress

#216 Update desktop-report-lifecycle-datasets.md
  powerbi-docs/desktop-report-lifecycle-datasets.md
Labels: Accepted, Linguistic Suggestion

#215 Update desktop-connect-to-data.md
  powerbi-docs/desktop-connect-to-data.md
Labels: Accepted, Linguistic Suggestion

#214 Update desktop-common-query-tasks.md
  powerbi-docs/desktop-common-query-tasks.md
Labels: Accepted, Linguistic Suggestion

#213 Update desktop-getting-started.md
  powerbi-docs/desktop-getting-started.md
Labels: Accepted, Linguistic Suggestion

#212 Update desktop-tutorial-row-level-security-onprem-ssas-tabular.md
  powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md
Labels: Accepted, Linguistic Suggestion

#211 Update desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-…
  powerbi-docs/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md
Labels: Accepted, Linguistic Suggestion

#210 Update desktop-shape-and-combine-data.md
  powerbi-docs/desktop-shape-and-combine-data.md
Labels: Accepted, Linguistic Suggestion

#209 Update desktop-quickstart-connect-to-data.md
  powerbi-docs/desktop-quickstart-connect-to-data.md
Labels: Accepted, Linguistic Suggestion

#229 Update desktop-mobile-geofiltering.md
  powerbi-docs/desktop-mobile-geofiltering.md
Labels: Accepted, Linguistic Suggestion

#223 Update power-bi-map-tips-and-tricks.md
  powerbi-docs/visuals/power-bi-map-tips-and-tricks.md
Labels: Linguistic Suggestion, Partially Accepted

#224 Update power-bi-visualization-customize-x-axis-and-y-axis.md
  powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md
Labels: Linguistic Suggestion, Partially Accepted

#225 Update power-bi-visualization-arcgis.md
  powerbi-docs/visuals/power-bi-visualization-arcgis.md
Labels: Accepted, Linguistic Suggestion

#226 Update power-bi-visualization-basic-area-chart.md
  powerbi-docs/visuals/power-bi-visualization-basic-area-chart.md
Labels: Accepted, Linguistic Suggestion

#227 Update power-bi-visualization-combo-chart.md
  powerbi-docs/visuals/power-bi-visualization-combo-chart.md
Labels: Accepted, Linguistic Suggestion

#230 Update power-bi-report-filter-preview.md
  powerbi-docs/power-bi-report-filter-preview.md
Labels: Accepted, Linguistic Suggestion

#233 Update desktop-slicer-filter-date-range.md
  powerbi-docs/visuals/desktop-slicer-filter-date-range.md
Labels: Accepted, Linguistic Suggestion

#240 Update desktop-connect-snowflake.md
  powerbi-docs/desktop-connect-snowflake.md
Labels: Accepted, Linguistic Suggestion

#239 Update desktop-connect-redshift.md
  powerbi-docs/desktop-connect-redshift.md
Labels: Accepted, Linguistic Suggestion

#244 Update desktop-bookmarks.md
  powerbi-docs/desktop-bookmarks.md
Labels: Accepted, Linguistic Suggestion

#245 Update end-user-report-filter.md
  powerbi-docs/consumer/end-user-report-filter.md
Labels: Accepted, Linguistic Suggestion
