Repository MicrosoftDocs/powerbi-docs.ko-kr, pull requests merged in 2019-07, with the labels that each got.

#268 Update azure-pbie-diag-logs.md
  powerbi-docs/developer/azure-pbie-diag-logs.md
Labels: Accepted, Linguistic Suggestion

#266 Update power-bi-visualization-influencers.md
  powerbi-docs/visuals/power-bi-visualization-influencers.md
Labels: Linguistic Suggestion, Partially Accepted

#278 Update desktop-visual-elements-for-reports.md
  powerbi-docs/desktop-visual-elements-for-reports.md
Labels: Accepted, Linguistic Suggestion

#276 Update service-datasets-admin-across-workspaces.md
  powerbi-docs/service-datasets-admin-across-workspaces.md
Labels: Accepted, Linguistic Suggestion

#273 Update service-create-workspaces.md
  powerbi-docs/service-create-workspaces.md
Labels: Accepted, Linguistic Suggestion

#272 Update service-create-the-new-workspaces.md
  powerbi-docs/service-create-the-new-workspaces.md
Labels: Accepted, Linguistic Suggestion

#279 Update desktop-tooltips.md
  powerbi-docs/desktop-tooltips.md
Labels: Accepted, Linguistic Suggestion

#284 Update power-bi-visualization-card.md
  powerbi-docs/visuals/power-bi-visualization-card.md
Labels: Accepted, Linguistic Suggestion

#277 Update power-bi-report-filter-preview.md
  powerbi-docs/power-bi-report-filter-preview.md
Labels: Accepted, Linguistic Suggestion

#280 Update desktop-performance-analyzer.md
  powerbi-docs/desktop-performance-analyzer.md
Labels: Accepted, Linguistic Suggestion

#281 Update desktop-slicer-filter-date-range.md
  powerbi-docs/visuals/desktop-slicer-filter-date-range.md
Labels: Accepted, Linguistic Suggestion

#283 Update desktop-upload-desktop-files.md
  powerbi-docs/desktop-upload-desktop-files.md
Labels: Accepted, Linguistic Suggestion

#282 Update desktop-create-and-manage-relationships.md
  powerbi-docs/desktop-create-and-manage-relationships.md
Labels: Accepted, Linguistic Suggestion

#275 Update service-datasets-certify.md
  powerbi-docs/service-datasets-certify.md
Labels: Linguistic Suggestion, Partially Accepted

#274 Update service-datasets-promote.md
  powerbi-docs/service-datasets-promote.md
Labels: Linguistic Suggestion, Partially Accepted

#286 Update power-bi-visualization-combo-chart.md
  powerbi-docs/visuals/power-bi-visualization-combo-chart.md
Labels: Linguistic Suggestion, Partially Accepted

#290 Update service-premium-what-is.md
  powerbi-docs/service-premium-what-is.md
Labels: Accepted, Linguistic Suggestion

#291 Update service-premium-capacity-manage.md
  powerbi-docs/service-premium-capacity-manage.md
Labels: Accepted, Linguistic Suggestion

#293 Update service-premium-capacity-optimize.md
  powerbi-docs/service-premium-capacity-optimize.md
Labels: Accepted, Linguistic Suggestion

#292 Update service-admin-premium-monitor-portal.md
  powerbi-docs/service-admin-premium-monitor-portal.md
Labels: Accepted, Linguistic Suggestion

#287 Update power-bi-visualization-kpi.md
  powerbi-docs/visuals/power-bi-visualization-kpi.md
Labels: Linguistic Suggestion, Partially Accepted

#288 Update service-new-workspaces.md
  powerbi-docs/service-new-workspaces.md
Labels: Accepted, Linguistic Suggestion

#289 Update power-bi-visualization-slicers.md
  powerbi-docs/visuals/power-bi-visualization-slicers.md
Labels: Accepted, Linguistic Suggestion

#294 Update service-premium-capacity-optimize.md
  powerbi-docs/service-premium-capacity-optimize.md
Labels: Accepted, Linguistic Suggestion

#297 Update service-flow-integration.md
  powerbi-docs/service-flow-integration.md
Labels: Accepted, Linguistic Suggestion

#295 Update service-premium-faq.md
  powerbi-docs/service-premium-faq.md
Labels: Linguistic Suggestion, Partially Accepted

#298 Update service-premium-capacity-optimize.md
  powerbi-docs/service-premium-capacity-optimize.md
Labels: Accepted, Linguistic Suggestion

#302 Update get-started.md
  powerbi-docs/report-server/get-started.md
Labels: Accepted, Linguistic Suggestion

#303 Update compare-report-server-service.md
  powerbi-docs/report-server/compare-report-server-service.md
Labels: Accepted, Linguistic Suggestion

#301 Update desktop-quick-measures.md
  powerbi-docs/desktop-quick-measures.md
Labels: Accepted, Linguistic Suggestion

#299 Update service-premium-capacity-scenarios.md
  powerbi-docs/service-premium-capacity-scenarios.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#300 Update service-admin-premium-workloads.md
  powerbi-docs/service-admin-premium-workloads.md
Labels: Accepted, Linguistic Suggestion

#304 Update service-premium-capacity-scenarios.md
  powerbi-docs/service-premium-capacity-scenarios.md
Labels: Accepted, Linguistic Suggestion

#305 Update service-premium-capacity-scenarios.md
  powerbi-docs/service-premium-capacity-scenarios.md
Labels: Accepted, Linguistic Suggestion

#306 Update service-premium-capacity-scenarios.md
  powerbi-docs/service-premium-capacity-scenarios.md
Labels: Accepted, Linguistic Suggestion

#307 Update desktop-slicer-filter-date-range.md
  powerbi-docs/visuals/desktop-slicer-filter-date-range.md
Labels: Linguistic Suggestion, Partially Accepted

#318 Update add-comments.md
  powerbi-docs/report-server/add-comments.md
Labels: Accepted, Linguistic Suggestion

#317 Update configure-scheduled-refresh.md
  powerbi-docs/report-server/configure-scheduled-refresh.md
Labels: Accepted, Linguistic Suggestion

#308 Update rls-faq.md
  powerbi-docs/includes/rls-faq.md
Labels: Accepted, Linguistic Suggestion

#311 Update developer-handbook-overview.md
  powerbi-docs/report-server/developer-handbook-overview.md
Labels: Accepted, Linguistic Suggestion

#310 Update data-sources.md
  powerbi-docs/report-server/data-sources.md
Labels: Accepted, Linguistic Suggestion
