Repository MicrosoftDocs/powerbi-docs.ko-kr, pull requests merged in 2020-02, with the labels that each got.

#754 Update service-template-apps-install-distribute.md
  powerbi-docs/service-template-apps-install-distribute.md
Labels: Accepted, Linguistic Suggestion

#753 Update service-admin-alternate-email-address-for-power-bi.md
  powerbi-docs/service-admin-alternate-email-address-for-power-bi.md
Labels: Accepted, Linguistic Suggestion

#759 Update service-connect-to-services.md
  powerbi-docs/service-connect-to-services.md
Labels: Accepted, Source Issue

#758 Update service-rename.md
  powerbi-docs/service-rename.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#757 Update service-admin-troubleshoot-unsupported-data-source-for-refresh.md
  powerbi-docs/service-admin-troubleshoot-unsupported-data-source-for-refresh.md
Labels: Accepted, Linguistic Suggestion

#760 Update service-delete.md
  powerbi-docs/service-delete.md
Labels: Accepted, Linguistic Suggestion

#762 Update service-connect-to-salesforce.md
  powerbi-docs/service-connect-to-salesforce.md
Labels: Accepted, Linguistic Suggestion

#764 Update service-connect-to-zendesk.md
  powerbi-docs/service-connect-to-zendesk.md
Labels: Accepted, Linguistic Suggestion

#765 Update desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md
  powerbi-docs/desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md
Labels: Linguistic Suggestion, Partially Accepted

#766 Update desktop-what-is-desktop.md
  powerbi-docs/desktop-what-is-desktop.md
Labels: Accepted, Linguistic Suggestion

#768 Update desktop-shape-and-combine-data.md
  powerbi-docs/desktop-shape-and-combine-data.md
Labels: Accepted, Linguistic Suggestion

#767 Update desktop-tutorial-facebook-analytics.md
  powerbi-docs/desktop-tutorial-facebook-analytics.md
Labels: Accepted, Linguistic Suggestion

#770 Update sample-tutorial-connect-to-the-samples.md
  powerbi-docs/sample-tutorial-connect-to-the-samples.md
Labels: Accepted, Linguistic Suggestion

#769 Update desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-…
  powerbi-docs/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#776 Update sample-procurement.md
  powerbi-docs/sample-procurement.md
Labels: Accepted

#771 Update sample-customer-profitability.md
  powerbi-docs/sample-customer-profitability.md
Labels: Accepted, Linguistic Suggestion

#774 Update sample-supplier-quality.md
  powerbi-docs/sample-supplier-quality.md
Labels: Accepted, Linguistic Suggestion

#773 Update sample-human-resources.md
  powerbi-docs/sample-human-resources.md
Labels: Accepted, Linguistic Suggestion

#775 Update sample-opportunity-analysis.md
  powerbi-docs/sample-opportunity-analysis.md
Labels: Accepted, Linguistic Suggestion

#772 Update sample-it-spend.md
  powerbi-docs/sample-it-spend.md
Labels: Accepted, Linguistic Suggestion

#761 Update service-connect-to-github.md
  powerbi-docs/service-connect-to-github.md
Labels: Accepted, Linguistic Suggestion

#780 Update desktop-relationships-understand.md
  powerbi-docs/desktop-relationships-understand.md
Labels: Accepted, Linguistic Suggestion

#778 Update sample-sales-and-marketing.md
  powerbi-docs/sample-sales-and-marketing.md
Labels: Accepted, Linguistic Suggestion

#777 Update sample-retail-analysis.md
  powerbi-docs/sample-retail-analysis.md
Labels: Accepted, Linguistic Suggestion

#782 Miss type
  powerbi-docs/desktop-custom-format-strings.md
Labels: Accepted, Linguistic Suggestion

#781 Update desktop-aggregations.md
  powerbi-docs/desktop-aggregations.md
Labels: Accepted, Linguistic Suggestion

#784 Update desktop-storage-mode.md
  powerbi-docs/desktop-storage-mode.md
Labels: Accepted, Linguistic Suggestion

#783 Update desktop-composite-models.md
  powerbi-docs/desktop-composite-models.md
Labels: Accepted, Linguistic Suggestion

#786 Update end-user-print.md
  powerbi-docs/consumer/end-user-print.md
Labels: Accepted, Linguistic Suggestion

#787 Update mobile-apps-home-page.md
  powerbi-docs/consumer/mobile/mobile-apps-home-page.md
Labels: Accepted, Linguistic Suggestion

#790 Update paginated-reports-subscriptions.md
  powerbi-docs/consumer/paginated-reports-subscriptions.md
Labels: Accepted, Linguistic Suggestion

#789 Update desktop-default-member-multidimensional-models.md
  powerbi-docs/desktop-default-member-multidimensional-models.md
Labels: Accepted, Linguistic Suggestion

#794 Update always-encrypted-support.md
  powerbi-docs/report-server/always-encrypted-support.md
Labels: Accepted, Linguistic Suggestion

#793 Update compare-report-server-service.md
  powerbi-docs/report-server/compare-report-server-service.md
Labels: Accepted, Linguistic Suggestion

#785 Update desktop-bidirectional-filtering.md
  powerbi-docs/desktop-bidirectional-filtering.md
Labels: Accepted, Linguistic Suggestion

#788 Update power-bi-data-sources.md
  powerbi-docs/power-bi-data-sources.md
Labels: Accepted, Linguistic Suggestion

#791 Update desktop-getting-started.md
  powerbi-docs/desktop-getting-started.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#792 Update desktop-common-query-tasks.md
  powerbi-docs/desktop-common-query-tasks.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#797 Update install-report-builder.md
  powerbi-docs/report-server/install-report-builder.md
Labels: Accepted, Linguistic Suggestion

#801 Update row-level-security-report-server.md
  powerbi-docs/report-server/row-level-security-report-server.md
Labels: Accepted, Linguistic Suggestion

#800 Update quickstart-create-powerbi-report.md
  powerbi-docs/report-server/quickstart-create-powerbi-report.md
Labels: Accepted, Linguistic Suggestion

#798 Update desktop-quickstart-learn-dax-basics.md
  powerbi-docs/desktop-quickstart-learn-dax-basics.md
Labels: Accepted, Linguistic Suggestion

#804 Update quickstart-create-paginated-report.md
  powerbi-docs/report-server/quickstart-create-paginated-report.md
Labels: Accepted, Linguistic Suggestion

#795 Update desktop-create-and-manage-relationships.md
  powerbi-docs/desktop-create-and-manage-relationships.md
Labels: Accepted, Linguistic Suggestion

#796 Update desktop-query-overview.md
  powerbi-docs/desktop-query-overview.md
Labels: Accepted, Linguistic Suggestion

#799 Update desktop-report-view.md
  powerbi-docs/desktop-report-view.md
Labels: Accepted, Linguistic Suggestion

#809 Update desktop-auto-date-time.md
  powerbi-docs/desktop-auto-date-time.md
Labels: Accepted, Linguistic Suggestion, Partially Accepted, Technical Issue

#802 Update desktop-connect-to-data.md
  powerbi-docs/desktop-connect-to-data.md
Labels: Accepted, Linguistic Suggestion

#803 Update power-bi-report-add-visualizations-i.md
  powerbi-docs/visuals/power-bi-report-add-visualizations-i.md
Labels: Linguistic Suggestion, Partially Accepted

#808 Update end-user-home.md
  powerbi-docs/consumer/end-user-home.md
Labels: Accepted, Linguistic Suggestion

#807 Update end-user-pdf.md
  powerbi-docs/consumer/end-user-pdf.md
Labels: Accepted, Linguistic Suggestion

#806 Update power-bi-visualization-customize-title-background-and-legend.md
  powerbi-docs/visuals/power-bi-visualization-customize-title-background-and-legend.md
Labels: Accepted, Linguistic Suggestion

#805 Update power-bi-report-add-visualizations-ii.md
  powerbi-docs/visuals/power-bi-report-add-visualizations-ii.md
Labels: Accepted, Linguistic Suggestion

#820 Update service-r-packages-support.md
  powerbi-docs/service-r-packages-support.md
Labels: Accepted, Linguistic Suggestion

#811 Update end-user-change-sort.md
  powerbi-docs/consumer/end-user-change-sort.md
Labels: Accepted, Linguistic Suggestion

#818 Update end-user-drill.md
  powerbi-docs/consumer/end-user-drill.md
Labels: Accepted, Linguistic Suggestion

#814 Update end-user-visual-type.md
  powerbi-docs/consumer/end-user-visual-type.md
Labels: Accepted, Linguistic Suggestion

#815 Update end-user-show-data.md
  powerbi-docs/consumer/end-user-show-data.md
Labels: Accepted, Linguistic Suggestion

#817 Update desktop-connect-using-generic-interfaces.md
  powerbi-docs/desktop-connect-using-generic-interfaces.md
Labels: Accepted, Linguistic Suggestion

#816 Update desktop-import-excel-workbooks.md
  powerbi-docs/desktop-import-excel-workbooks.md
Labels: Accepted, Linguistic Suggestion

#822 Update end-user-subscribe.md
  powerbi-docs/consumer/end-user-subscribe.md
Labels: Accepted, Linguistic Suggestion

#821 Update end-user-focus.md
  powerbi-docs/consumer/end-user-focus.md
Labels: Accepted, Linguistic Suggestion

#825 Update end-user-preview-features.md
  powerbi-docs/consumer/end-user-preview-features.md
Labels: Accepted, Linguistic Suggestion

#823 Update desktop-enter-data-directly-into-desktop.md
  powerbi-docs/desktop-enter-data-directly-into-desktop.md
Labels: Accepted, Linguistic Suggestion

#828 Update end-user-app-view.md
  powerbi-docs/consumer/end-user-app-view.md
Labels: Accepted, Linguistic Suggestion

#829 Update mobile-reports-in-the-mobile-apps.md
  powerbi-docs/consumer/mobile/mobile-reports-in-the-mobile-apps.md
Labels: Accepted, Linguistic Suggestion

#827 Update desktop-sap-hana-encryption.md
  powerbi-docs/desktop-sap-hana-encryption.md
Labels: Accepted, Technical Issue

#812 Update desktop-connect-to-web-by-example.md
  powerbi-docs/desktop-connect-to-web-by-example.md
Labels: Accepted, Linguistic Suggestion

#813 Update desktop-report-lifecycle-datasets.md
  powerbi-docs/desktop-report-lifecycle-datasets.md
Labels: Accepted, Linguistic Suggestion

#819 Update desktop-r-scripts.md
  powerbi-docs/desktop-r-scripts.md
Labels: Accepted, Linguistic Suggestion

#824 Update desktop-ssas-multidimensional.md
  powerbi-docs/desktop-ssas-multidimensional.md
Labels: Accepted, Linguistic Suggestion

#826 Update desktop-connect-azure-cost-management.md
  powerbi-docs/desktop-connect-azure-cost-management.md
Labels: Linguistic Suggestion, Partially Accepted

#830 Update desktop-assume-referential-integrity.md
  powerbi-docs/desktop-assume-referential-integrity.md
Labels: Accepted, Linguistic Suggestion

#831 Update desktop-sap-bw-connector.md
  powerbi-docs/desktop-sap-bw-connector.md
Labels: Accepted, Linguistic Suggestion
