Repository MicrosoftDocs/powerbi-docs.ko-kr, pull requests merged in 2020-03, with the labels that each got.

#833 Update service-google-analytics-connector.md
  powerbi-docs/service-google-analytics-connector.md
Labels: Accepted, Linguistic Suggestion

#842 Update mobile-windows-10-phone-app-get-started.md
  powerbi-docs/consumer/mobile/mobile-windows-10-phone-app-get-started.md
Labels: Accepted, Linguistic Suggestion

#835 Update mobile-apps-scan-barcode-iphone.md
  powerbi-docs/consumer/mobile/mobile-apps-scan-barcode-iphone.md
Labels: Accepted, Linguistic Suggestion

#836 Update mobile-iphone-app-get-started.md
  powerbi-docs/consumer/mobile/mobile-iphone-app-get-started.md
Labels: Accepted, Linguistic Suggestion

#839 Update mobile-android-app-get-started.md
  powerbi-docs/consumer/mobile/mobile-android-app-get-started.md
Labels: Accepted, Linguistic Suggestion

#840 Update desktop-measures.md
  powerbi-docs/desktop-measures.md
Labels: Accepted, Linguistic Suggestion

#841 Update desktop-import-and-display-kpis.md
  powerbi-docs/desktop-import-and-display-kpis.md
Labels: Accepted, Linguistic Suggestion

#843 Update desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md
  powerbi-docs/desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#844 Update desktop-automatic-page-refresh.md
  powerbi-docs/desktop-automatic-page-refresh.md
Labels: Accepted, Linguistic Suggestion

#846 Update desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-…
  powerbi-docs/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md
Labels: Accepted, Linguistic Suggestion

#849 Update desktop-bookmarks.md
  powerbi-docs/desktop-bookmarks.md
Labels: Accepted, Linguistic Suggestion

#850 Update desktop-tutorial-row-level-security-onprem-ssas-tabular.md
  powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md
Labels: Accepted, Linguistic Suggestion

#832 Update mobile-set-data-alerts-in-the-mobile-apps.md
  powerbi-docs/consumer/mobile/mobile-set-data-alerts-in-the-mobile-apps.md
Labels: Accepted, Linguistic Suggestion

#834 Update desktop-mobile-geofiltering.md
  powerbi-docs/desktop-mobile-geofiltering.md
Labels: Accepted, Linguistic Suggestion

#837 Update desktop-calculated-columns.md
  powerbi-docs/desktop-calculated-columns.md
Labels: Accepted, Linguistic Suggestion

#838 Update desktop-calculated-tables.md
  powerbi-docs/desktop-calculated-tables.md
Labels: Accepted, Linguistic Suggestion

#845 Update desktop-insights.md
  powerbi-docs/desktop-insights.md
Labels: Accepted, Linguistic Suggestion

#847 Typo correction
  powerbi-docs/desktop-automatic-page-refresh.md
Labels: Linguistic Suggestion, Partially Accepted

#848 Update desktop-insights-find-where-different.md
  powerbi-docs/desktop-insights-find-where-different.md
Labels: Accepted, Linguistic Suggestion

#851 Update desktop-aggregations.md
  powerbi-docs/desktop-aggregations.md
Labels: Accepted, Linguistic Suggestion

#855 Update desktop-r-visuals.md
  powerbi-docs/desktop-r-visuals.md
Labels: Accepted, Linguistic Suggestion

#854 Update desktop-composite-models.md
  powerbi-docs/desktop-composite-models.md
Labels: Accepted, Linguistic Suggestion

#857 Update desktop-bidirectional-filtering.md
  powerbi-docs/desktop-bidirectional-filtering.md
Labels: Accepted, Linguistic Suggestion

#858 Update desktop-directquery-about.md
  powerbi-docs/desktop-directquery-about.md
Labels: Accepted, Linguistic Suggestion

#860 Update power-bi-report-display-settings.md
  powerbi-docs/power-bi-report-display-settings.md
Labels: Accepted, Linguistic Suggestion

#852 Update desktop-report-themes.md
  powerbi-docs/desktop-report-themes.md
Labels: Accepted, Linguistic Suggestion

#853 Update desktop-cross-report-drill-through.md
  powerbi-docs/desktop-cross-report-drill-through.md
Labels: Accepted, Linguistic Suggestion

#859 Update desktop-gridlines-snap-to-grid.md
  powerbi-docs/desktop-gridlines-snap-to-grid.md
Labels: Accepted, Linguistic Suggestion

#861 Update power-bi-data-sources.md
  powerbi-docs/power-bi-data-sources.md
Labels: Accepted, Linguistic Suggestion

#863 Update desktop-add-custom-column.md
  powerbi-docs/desktop-add-custom-column.md
Labels: Accepted, Linguistic Suggestion

#864 Update desktop-data-source-prerequisites.md
  powerbi-docs/desktop-data-source-prerequisites.md
Labels: Accepted, Linguistic Suggestion

#865 Update desktop-data-view.md
  powerbi-docs/desktop-data-view.md
Labels: Accepted, Linguistic Suggestion

#869 Update power-bi-reports-add-text-and-shapes.md
  powerbi-docs/power-bi-reports-add-text-and-shapes.md
Labels: Accepted, Linguistic Suggestion

#870 Update service-add-hyperlink-to-text-box.md
  powerbi-docs/service-add-hyperlink-to-text-box.md
Labels: Accepted, Linguistic Suggestion

#872 Update desktop-connect-to-data.md
  powerbi-docs/desktop-connect-to-data.md
Labels: Accepted, Linguistic Suggestion

#873 Update desktop-custom-format-strings.md
  powerbi-docs/desktop-custom-format-strings.md
Labels: Accepted, Linguistic Suggestion

#874 Update desktop-conditional-format-visual-titles.md
  powerbi-docs/desktop-conditional-format-visual-titles.md
Labels: Accepted, Linguistic Suggestion

#875 Update desktop-sharepoint-online-list.md
  powerbi-docs/desktop-sharepoint-online-list.md
Labels: Accepted, Linguistic Suggestion

#866 Update desktop-slicer-filter-date-range.md
  powerbi-docs/visuals/desktop-slicer-filter-date-range.md
Labels: Accepted, Linguistic Suggestion

#876 Update power-bi-report-visualizations.md
  powerbi-docs/visuals/power-bi-report-visualizations.md
Labels: Accepted, Linguistic Suggestion

#877 Update power-bi-data-points.md
  powerbi-docs/visuals/power-bi-data-points.md
Labels: Accepted, Linguistic Suggestion

#878 Update desktop-use-onedrive-business-links.md
  powerbi-docs/desktop-use-onedrive-business-links.md
Labels: Accepted, Linguistic Suggestion

#879 Update service-share-reports.md
  powerbi-docs/service-share-reports.md
Labels: Accepted, Linguistic Suggestion

#862 Update desktop-add-column-from-example.md
  powerbi-docs/desktop-add-column-from-example.md
Labels: Accepted, Linguistic Suggestion

#867 Update power-bi-slicer-filter-responsive.md
  powerbi-docs/power-bi-slicer-filter-responsive.md
Labels: Accepted, Linguistic Suggestion

#880 Update service-reports-show-data.md
  powerbi-docs/visuals/service-reports-show-data.md
Labels: Accepted, Linguistic Suggestion

#882 Update desktop-report-view.md
  powerbi-docs/desktop-report-view.md
Labels: Accepted, Linguistic Suggestion

#885 Update service-publish-to-web.md
  powerbi-docs/service-publish-to-web.md
Labels: Accepted, Linguistic Suggestion

#886 Update service-premium-incremental-refresh.md
  powerbi-docs/service-premium-incremental-refresh.md
Labels: Accepted, Technical Issue

#868 Update desktop-relationship-view.md
  powerbi-docs/desktop-relationship-view.md
Labels: Accepted, Linguistic Suggestion

#888 Update end-user-experience.md
  powerbi-docs/consumer/end-user-experience.md
Labels: Accepted, Linguistic Suggestion

#891 Update power-bi-hyperlinks-in-tables.md
  powerbi-docs/power-bi-hyperlinks-in-tables.md
Labels: Accepted, Linguistic Suggestion

#883 Update service-tips-and-tricks-for-color-formatting.md
  powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md
Labels: Accepted, Linguistic Suggestion

#884 Update service-reports-visual-interactions.md
  powerbi-docs/service-reports-visual-interactions.md
Labels: Accepted, Linguistic Suggestion

#889 Update power-bi-visualization-card.md
  powerbi-docs/visuals/power-bi-visualization-card.md
Labels: Accepted, Linguistic Suggestion

#895 Update desktop-sort-by-column.md
  powerbi-docs/desktop-sort-by-column.md
Labels: Accepted, Linguistic Suggestion

#896 Update power-bi-visualization-influencers.md
  powerbi-docs/visuals/power-bi-visualization-influencers.md
Labels: Accepted, Linguistic Suggestion

#897 Update power-bi-visualization-kpi.md
  powerbi-docs/visuals/power-bi-visualization-kpi.md
Labels: Accepted, Linguistic Suggestion

#898 Update desktop-matrix-visual.md
  powerbi-docs/visuals/desktop-matrix-visual.md
Labels: Accepted, Linguistic Suggestion

#899 Update power-bi-visualization-q-and-a.md
  powerbi-docs/visuals/power-bi-visualization-q-and-a.md
Labels: Accepted, Linguistic Suggestion

#892 Update power-bi-visualization-decomposition-tree.md
  powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md
Labels: Linguistic Suggestion, Partially Accepted

#894 Update power-bi-visualization-filled-maps-choropleths.md
  powerbi-docs/visuals/power-bi-visualization-filled-maps-choropleths.md
Labels: Linguistic Suggestion, Partially Accepted

#900 Update power-bi-visualization-funnel-charts.md
  powerbi-docs/visuals/power-bi-visualization-funnel-charts.md
Labels: Accepted, Linguistic Suggestion

#901 Update service-r-visuals.md
  powerbi-docs/visuals/service-r-visuals.md
Labels: Accepted, Linguistic Suggestion

#902 Update power-bi-visualization-combo-chart.md
  powerbi-docs/visuals/power-bi-visualization-combo-chart.md
Labels: Accepted, Linguistic Suggestion

#904 Update desktop-ribbon-charts.md
  powerbi-docs/visuals/desktop-ribbon-charts.md
Labels: Accepted, Linguistic Suggestion

#906 Update desktop-shape-map.md
  powerbi-docs/visuals/desktop-shape-map.md
Labels: Accepted, Linguistic Suggestion

#908 Update power-bi-visualization-tables.md
  powerbi-docs/visuals/power-bi-visualization-tables.md
Labels: Accepted, Linguistic Suggestion

#890 Update desktop-report-themes.md
  powerbi-docs/desktop-report-themes.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#907 Update power-bi-visualization-slicers.md
  powerbi-docs/visuals/power-bi-visualization-slicers.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#905 Update power-bi-visualization-scatter.md
  powerbi-docs/visuals/power-bi-visualization-scatter.md
Labels: Accepted, Linguistic Suggestion

#903 Update power-bi-visualization-radial-gauge-charts.md
  powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md
Labels: Linguistic Suggestion, Partially Accepted, Technical Issue

#918 Update service-admin-premium-purchase.md
  powerbi-docs/service-admin-premium-purchase.md
Labels: Accepted

#909 Update power-bi-visualization-treemaps.md
  powerbi-docs/visuals/power-bi-visualization-treemaps.md
Labels: Accepted, Linguistic Suggestion

#910 Update power-bi-visualization-waterfall-charts.md
  powerbi-docs/visuals/power-bi-visualization-waterfall-charts.md
Labels: Accepted, Linguistic Suggestion

#911 Update q-and-a-intro.md
  powerbi-docs/natural-language/q-and-a-intro.md
Labels: Accepted, Linguistic Suggestion

#912 Update q-and-a-tooling-intro.md
  powerbi-docs/natural-language/q-and-a-tooling-intro.md
Labels: Accepted, Linguistic Suggestion

#913 Update q-and-a-tooling-teach-q-and-a.md
  powerbi-docs/natural-language/q-and-a-tooling-teach-q-and-a.md
Labels: Accepted, Linguistic Suggestion

#915 Update q-and-a-limitations.md
  powerbi-docs/natural-language/q-and-a-limitations.md
Labels: Accepted, Linguistic Suggestion

#916 Update desktop-accessibility-consuming-tools.md
  powerbi-docs/desktop-accessibility-consuming-tools.md
Labels: Accepted, Linguistic Suggestion

#917 Update desktop-accessibility-keyboard-shortcuts.md
  powerbi-docs/desktop-accessibility-keyboard-shortcuts.md
Labels: Accepted, Linguistic Suggestion

#919 Update service-premium-large-models.md
  powerbi-docs/service-premium-large-models.md
Labels: Accepted, Linguistic Suggestion

#920 Update service-encryption-byok.md
  powerbi-docs/service-encryption-byok.md
Labels: Accepted, Linguistic Suggestion

#921 Update paginated-reports-enter-data.md
  powerbi-docs/paginated-reports-enter-data.md
Labels: Accepted, Linguistic Suggestion

#922 Update service-gateway-sso-kerberos.md
  powerbi-docs/service-gateway-sso-kerberos.md
Labels: Accepted, Linguistic Suggestion

#914 Update q-and-a-tooling-advanced.md
  powerbi-docs/natural-language/q-and-a-tooling-advanced.md
Labels: Linguistic Suggestion, Partially Accepted

#925 Update service-premium-incremental-refresh.md
  powerbi-docs/service-premium-incremental-refresh.md
Labels: Accepted, Linguistic Suggestion

#926 Update service-new-look.md
  powerbi-docs/service-new-look.md
Labels: Accepted, Linguistic Suggestion

#927 Update paginated-reports-view-power-bi-service.md
  powerbi-docs/consumer/paginated-reports-view-power-bi-service.md
Labels: Accepted, Linguistic Suggestion

#929 Update power-bi-visualization-filled-maps-choropleths.md
  powerbi-docs/visuals/power-bi-visualization-filled-maps-choropleths.md
Labels: Accepted, Linguistic Suggestion

#928 Update scheduled-refresh.md
  powerbi-docs/report-server/scheduled-refresh.md
Labels: Accepted, Linguistic Suggestion

#930 Update desktop-tips-and-tricks-for-creating-reports.md
  powerbi-docs/desktop-tips-and-tricks-for-creating-reports.md
Labels: Accepted, Linguistic Suggestion

#932 Update power-bi-visualization-export-data.md
  powerbi-docs/visuals/power-bi-visualization-export-data.md
Labels: Accepted, Linguistic Suggestion

#933 Update paginated-reports-enter-data.md
  powerbi-docs/paginated-reports-enter-data.md
Labels: Accepted, Linguistic Suggestion

#934 Update paginated-reports-embedded-data-source.md
  powerbi-docs/paginated-reports-embedded-data-source.md
Labels: Accepted, Linguistic Suggestion

#935 Update report-builder-shared-datasets.md
  powerbi-docs/report-builder-shared-datasets.md
Labels: Accepted, Linguistic Suggestion

#936 Update paginated-reports-save-to-power-bi-service.md
  powerbi-docs/paginated-reports-save-to-power-bi-service.md
Labels: Accepted, Linguistic Suggestion

#937 Update service-admin-failover.md
  powerbi-docs/service-admin-failover.md
Labels: Accepted, Linguistic Suggestion

#931 Update service-analyze-in-excel.md
  powerbi-docs/service-analyze-in-excel.md
Labels: Accepted, Linguistic Suggestion

#938 Update desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md
  powerbi-docs/desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md
Labels: Accepted, Linguistic Suggestion

#939 Update desktop-tutorial-row-level-security-onprem-ssas-tabular.md
  powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md
Labels: Accepted, Linguistic Suggestion

#940 Update visual-project-structure.md
  powerbi-docs/developer/visuals/visual-project-structure.md
Labels: Accepted, Linguistic Suggestion

#942 Update service-admin-premium-workloads.md
  powerbi-docs/service-admin-premium-workloads.md
Labels: Accepted, Linguistic Suggestion

#943 Update service-encryption-byok.md
  powerbi-docs/service-encryption-byok.md
Labels: Accepted, Linguistic Suggestion

#941 Update service-admin-rls.md
  powerbi-docs/service-admin-rls.md
Labels: Accepted, Linguistic Suggestion

#946 Update service-modern-usage-metrics.md
  powerbi-docs/service-modern-usage-metrics.md
Labels: Accepted, Linguistic Suggestion

#947 Update relationships-many-to-many.md
  powerbi-docs/guidance/relationships-many-to-many.md
Labels: Accepted, Linguistic Suggestion

#948 Update report-drillthrough.md
  powerbi-docs/guidance/report-drillthrough.md
Labels: Accepted, Linguistic Suggestion

#944 Update service-admin-manage-your-data-storage-in-power-bi.md
  powerbi-docs/service-admin-manage-your-data-storage-in-power-bi.md
Labels: Accepted, Linguistic Suggestion
